### ISSUE TITLE
Increase vm boot timeout to 500 seconds or more

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/terraform-nomad-hive#24]
May be..I added this as the tests failed with following error message:
https://github.com/fredrikhgrelland/terraform-nomad-hive/blob/133af774e0553f83f30f5bad5e554a869a90441a/Vagrantfile.default#L4
```
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
make: *** [up] Error 1
Error: Process completed with exit code 2.
```
The default timeout value is 300 seconds : https://www.vagrantup.com/docs/vagrantfile/machine_settings#config-vm-boot_timeout
I will create an issue so we can keep a track of this.

_Originally posted by @Neha-Sinha2305 in https://github.com/fredrikhgrelland/terraform-nomad-hive/pull/22#discussion_r502345544_

**Comment by zhenik** [comment]
Was fixed here https://github.com/fredrikhgrelland/terraform-nomad-hive/pull/22
