### ISSUE TITLE
Error pulling hive image "context deadline exceeded

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/terraform-nomad-hive#52]
## Current behaviour
Getting this error when running `make up` from a mac behind transparent proxy (does not show when VPN is off). `CUSTOM_CA`, `SSL_CERT_FILE` and `CURL_CA_BUNDLE` are all set. 
![image](https://user-images.githubusercontent.com/51820995/98529419-ded9bc80-227d-11eb-9d9e-38a16d420eca.png)

## Expected behaviour
Successful download of image

## How to reproduce?
Run `make up` with mac behind transparent proxy

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by pdmthorsrud** [comment]
Could this be as simple as the fact that it takes absolutely forever to download something with VPN enabled? I'll see if I can extend the timer or something.

@zhenik do you know anything about this?

**Comment by zhenik** [comment]
Could for debug install CERTS inside the box and try run (inside the box) `terraform init`, `terraform apply`?

**Comment by pdmthorsrud** [comment]
do you actually think it's a problem with certs? I'll go inside the box and double check that all certs are present, but I think it is something else.
