### ISSUE TITLE
Our semver release action is out of date and not working anymore

### ISSUE THREAD

**Issue by pdmthorsrud** [fredrikhgrelland/terraform-nomad-hive#62]
## Current behaviour
We are using set-env in the workflows, which is deprecated. https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
![image](https://user-images.githubusercontent.com/51820995/99782905-0bad8f80-2b1a-11eb-88a2-0c7eb8369023.png)

## Expected behaviour
The variables are set successfully

## How to reproduce?
Run the workflow

## Suggestion(s)/solution(s) [Optional]
Follow this pattern: https://github.com/fredrikhgrelland/vagrant-hashistack-template/commit/5e4f8a3732f61f80ae0b22826764499c6878b5d1

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
Actually, looking into it, we are using an action that uses this feature, it is not _our_ code. Checking now to see if there is newer relase available

**Comment by dangernil** [comment]
There is someone who wants to merge a fix for the set-env, will that fix it? https://github.com/zwaldowski/semver-release-action/pull/11#issuecomment-730397756

**Comment by pdmthorsrud** [comment]
There is a PR fixing this problem https://github.com/zwaldowski/semver-release-action/pull/11 
There is a PR from 12th of September that hasn't been merged though, so I guess we'll have to see.

**Comment by pdmthorsrud** [comment]
Oops, should have been linked to #61 which fixed this problem. Closing
